export enum RabbitMQ {
  ProcesoDeterminadoQueue = 'procesoDeterminados',
}

export enum ProcesoDeterminadoMSG {
  CREATE = 'CREATE_PROCESO_DETERMINADO',
  FIND_ALL = 'FIND_PROCESO_DETERMINADOS',
  FIND_ONE = 'FIND_PROCESO_DETERMINADO',
  UPDATE = 'UPDATE_PROCESO_DETERMINADO',
  DELETE = 'DELETE_PROCESO_DETERMINADO',
}
